# global:
#   scrape_interval: 10s
scrape_configs:
#   - job_name: prometheus
#     static_configs:
#       - targets:
#         - prometheus:9090
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      # - targets: ['otel-collector:8888']
#   - job_name: 'blackbox-exporter'
#     metrics_path: /probe
#     params:
#       module: [http_2xx]  # You can define other modules too
#     static_configs:
#       - targets:
#         - http://single-spa-react:4000
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - source_labels: [__param_target]
#         target_label: instance
#       - target_label: __address__
#         replacement: blackbox-exporter:9115

#       - source_labels: [__param_target]
#         regex: http://single-spa-react:4000
#         target_label: app_name
#         replacement: single_spa_react
