{
 "title": "Service APM - MongoDB",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(db_operation_duration_seconds_bucket, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mongo operation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_operation_duration_seconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(db_operation_duration_seconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Mongo error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(db_operation_errors_total{service_name=\"$service\"}[$__rate_interval])) / (sum(rate(db_operations_total{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB ops/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops / s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db_operation) (rate(db_operation_duration_seconds_count{service_name=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Largest"
    }
   ]
  }
 ]
}