{
 "title": "Service APM",
 "time": { "from": "2025-12-27T11:11:05.559Z", "to": "2025-12-27T11:13:43.076Z" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_bucket, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "High value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response duration bucket",
   "type": "heatmap",
   "description": "Cumulative counters for the observation buckets (Measures the duration of inbound HTTP requests.)\n\n**Type:** *counter*\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_duration_milliseconds_bucket{ service_name=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Response duration series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "95% duration"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "99% duration"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "50% duration"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service_name=\"$service\", http_status_code=\"500\"}[$__rate_interval])) / sum(rate(http_server_duration_milliseconds_count[$__rate_interval]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 vs 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{service_name=\"$service\", http_status_code=\"500\"}[$__rate_interval]) * 100",
     "legendFormat": "500"
    },
    {
     "expr": "rate(http_server_duration_milliseconds_count{service_name=\"$service\", http_status_code=\"200\"}[$__rate_interval]) * 100",
     "legendFormat": "200"
    }
   ]
  }
 ]
}