{
 "title": "SPA App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Web vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(frontend_web_vitals_ttfb_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(frontend_web_vitals_ttfb_milliseconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(frontend_web_vitals_ttfb_milliseconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "95% of Route load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route_from, route_to) (rate(frontend_navigation_route_switch_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(frontend_web_vitals_fcp_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(frontend_web_vitals_fcp_milliseconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(frontend_web_vitals_fcp_milliseconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "95% endpoint calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_endpoint) (rate(frontend_endpoint_duration_milliseconds_bucket[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% of endpoint duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, http_endpoint) (rate(frontend_endpoint_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average endpoint calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(http_endpoint) (rate(frontend_endpoint_duration_milliseconds_sum[$__rate_interval]))) / sum by(http_endpoint) (rate(frontend_endpoint_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average endpoint duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(http_endpoint) (rate(frontend_endpoint_duration_milliseconds_sum[$__rate_interval])) / sum by(http_endpoint) (rate(frontend_endpoint_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(frontend_endpoint_duration_milliseconds_bucket{le=\"250.0\"}[$__rate_interval])) \n  + \n  sum(rate(frontend_endpoint_duration_milliseconds_bucket{le=\"1000.0\"}[$__rate_interval]))\n) \n/ \n2 \n/ \nsum(rate(frontend_endpoint_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}