{
 "title": "Traces",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend trace sizes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(round(sum(rate(traces_service_graph_request_total[$__rate_interval])) / sum(rate(traces_service_graph_request_total{client=\"spa-react\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan out",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  label_replace(\n    rate(traces_service_graph_request_total[$__rate_interval]), \n    \"service_name\", \"$1\", \"client\", \"(.*)\"\n  )\n)\n/\nsum by (service_name) (\n  label_replace(\n    rate(traces_service_graph_request_total[$__rate_interval]), \n    \"service_name\", \"$1\", \"server\", \"(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service dependency degree",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(client) (sum by(client, server) (rate(traces_service_graph_request_total{server!=\"unknown\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SPA app traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"spa-react\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}