apiVersion: 1

datasources:
  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData: {}

  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST

  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
        httpMethod: GET
        tracesToLogs:
            datasourceUid: 'loki'
        tracesToMetrics:
            datasourceUid: 'prometheus'
        serviceMap:
            datasourceUid: 'prometheus'
        nodeGraph:
            enabled: true
